---
all:
  children:

    proxmox_hosts:
      hosts:
        nimbus:
          ansible_host: 192.168.12.156
          ansible_user: root
          host_features:
            proxmox: true

        zebulon:
          ansible_host: 192.168.40.6
          ansible_user: root
          host_features:
            proxmox: true

    debian_containers:
      hosts:
        docker-ct:
          ansible_host: 192.168.40.214
          ansible_user: root
          host_features:
            docker: true
            lxc_container: true

    docker_hosts:
      hosts:
        docker-ct:

    lxc_guests:
      hosts:
        docker-ct:

    ubuntu_servers:
      hosts:
        ubuntu-server:
          ansible_host: 192.168.40.116
          ansible_user: hackwell

    managed_linux:
      children:
        proxmox_hosts:
        debian_containers:
        ubuntu_servers:

    monitoring_enabled:
      children:
        managed_linux:

  vars:
    ansible_python_interpreter: /usr/bin/python3
