---
health_check_disk_warning_percent: 80
health_check_disk_critical_percent: 90

health_check_inode_warning_percent: 80
health_check_inode_critical_percent: 90

health_check_memory_warning_percent: 80
health_check_memory_critical_percent: 90

health_check_report_dir: "{{ playbook_dir }}/../reports"
